global:
  scrape_interval: 5s  # how often to scrape

scrape_configs:
  - job_name: "media_downloader_app"
    static_configs:
      - targets: ["172.17.0.1:8000"]  # change this if needed
# If Prometheus is running inside Docker and your app is running on the host, this address lets Docker access the host machine.